cafile: "/Users/adanchenkov/.ssl/CSI-HTTPS-INSPECTION-CA.pem"
httpProxy: "http://adanchenkov:Pesiki%21@198.77.155.252:800"
httpsProxy: "http://adanchenkov:Pesiki%21@198.77.155.252:800"
httpTimeout: 500000
